[project]
name = "pyxel-game-dev"
version = "0.1.0"
description = "Pyxel and Esper game development experiments."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "esper>=3.4",
    "pymunk>=7.2.0",
    "pyxel>=2.5.10",
]
