[project]
name = "pyxel-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "esper>=3.4",
    "pymunk>=7.2.0",
    "pyxel>=2.5.10",
]
